# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13d26becc8f74917c921fba52a656bdf6f540a5ef823939e37b4ec16fc7dcfeef83f13e0b89831502d13d9c19d2140040f7ce241c3e41ae35108ca05b1be370a

test:
  secret_key_base: d3fc60b9fbf7f70760b4593171666bfe5d3d3b8f3e9235de96fb9c677397c4ab3c8ed5b0ebddff03572f1505211e20ee9706cc3e036fea6fc3f855fef13c862e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
